/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PriceBreakdown = IDL.Record({
  'amenityBonus' : IDL.Float64,
  'floorBonus' : IDL.Float64,
  'locationMultiplier' : IDL.Float64,
  'basePrice' : IDL.Float64,
  'ageDiscount' : IDL.Float64,
});
export const PredictionResult = IDL.Record({
  'estimatedPrice' : IDL.Float64,
  'breakdown' : PriceBreakdown,
  'pricePerSqft' : IDL.Float64,
  'confidence' : IDL.Text,
});
export const PredictionInput = IDL.Record({
  'bhk' : IDL.Nat,
  'floor' : IDL.Nat,
  'totalFloors' : IDL.Nat,
  'propertyType' : IDL.Text,
  'area' : IDL.Float64,
  'city' : IDL.Text,
  'houseAge' : IDL.Nat,
  'bathrooms' : IDL.Nat,
  'furnishing' : IDL.Text,
  'parking' : IDL.Bool,
  'location' : IDL.Text,
});
export const PredictionRecord = IDL.Record({
  'result' : PredictionResult,
  'timestamp' : IDL.Int,
  'input' : PredictionInput,
});

export const idlService = IDL.Service({
  'getPredictionStats' : IDL.Func([], [IDL.Nat], ['query']),
  'getRecentPredictions' : IDL.Func([], [IDL.Vec(PredictionRecord)], ['query']),
  'predictPrice' : IDL.Func([PredictionInput], [PredictionResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PriceBreakdown = IDL.Record({
    'amenityBonus' : IDL.Float64,
    'floorBonus' : IDL.Float64,
    'locationMultiplier' : IDL.Float64,
    'basePrice' : IDL.Float64,
    'ageDiscount' : IDL.Float64,
  });
  const PredictionResult = IDL.Record({
    'estimatedPrice' : IDL.Float64,
    'breakdown' : PriceBreakdown,
    'pricePerSqft' : IDL.Float64,
    'confidence' : IDL.Text,
  });
  const PredictionInput = IDL.Record({
    'bhk' : IDL.Nat,
    'floor' : IDL.Nat,
    'totalFloors' : IDL.Nat,
    'propertyType' : IDL.Text,
    'area' : IDL.Float64,
    'city' : IDL.Text,
    'houseAge' : IDL.Nat,
    'bathrooms' : IDL.Nat,
    'furnishing' : IDL.Text,
    'parking' : IDL.Bool,
    'location' : IDL.Text,
  });
  const PredictionRecord = IDL.Record({
    'result' : PredictionResult,
    'timestamp' : IDL.Int,
    'input' : PredictionInput,
  });
  
  return IDL.Service({
    'getPredictionStats' : IDL.Func([], [IDL.Nat], ['query']),
    'getRecentPredictions' : IDL.Func(
        [],
        [IDL.Vec(PredictionRecord)],
        ['query'],
      ),
    'predictPrice' : IDL.Func([PredictionInput], [PredictionResult], []),
  });
};

export const init = ({ IDL }) => { return []; };