/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PredictionInput {
  'bhk' : bigint,
  'floor' : bigint,
  'totalFloors' : bigint,
  'propertyType' : string,
  'area' : number,
  'city' : string,
  'houseAge' : bigint,
  'bathrooms' : bigint,
  'furnishing' : string,
  'parking' : boolean,
  'location' : string,
}
export interface PredictionRecord {
  'result' : PredictionResult,
  'timestamp' : bigint,
  'input' : PredictionInput,
}
export interface PredictionResult {
  'estimatedPrice' : number,
  'breakdown' : PriceBreakdown,
  'pricePerSqft' : number,
  'confidence' : string,
}
export interface PriceBreakdown {
  'amenityBonus' : number,
  'floorBonus' : number,
  'locationMultiplier' : number,
  'basePrice' : number,
  'ageDiscount' : number,
}
export interface _SERVICE {
  'getPredictionStats' : ActorMethod<[], bigint>,
  'getRecentPredictions' : ActorMethod<[], Array<PredictionRecord>>,
  'predictPrice' : ActorMethod<[PredictionInput], PredictionResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];